### PR TITLE
Hello world programme in java

### PR DESCRIPTION
**Pull request by sattwik21**
helloworld programme  in java language

### CODE REVIEW

**Comment by Hyper-Matrix** [comment]
@sattwik21 are you sure your code works? I cant find a class in the java file. Also please follow the guidelines mentioned in the readme of this repo.

**Review by sattwik21 — COMMENTED** [review]
Updated the hello world file

**Comment by Hyper-Matrix** [comment]
LGTM

**Review by Hyper-Matrix — APPROVED** [review]

**Comment by Hyper-Matrix** [comment]
@GunjanGiri Thanks for merging but please approve it before merging.

**Comment by GunjanGiri** [comment]
@Hyper-Matrix Sure

**Pull request merged**
