### PR TITLE
A hello world programme in C language

### PR DESCRIPTION
**Pull request by sattwik21**
A hello world programme in C language

### CODE REVIEW

**Comment by Hyper-Matrix** [comment]
@sattwik21 Please write a proper title and a description

**Comment by Hyper-Matrix** [comment]
LGTM

**Review by Hyper-Matrix — APPROVED** [review]

**Review by C3Suryansu — COMMENTED** [review]
Create a folder with the name of your language and then place the code file inside it. The structure of the Pull Request should be as per mentioned in the readme.md file in the Hello World repository.

**Review by C3Suryansu — APPROVED** [review]
Looks ok

**Pull request merged**
