### PR TITLE
Hello World in GO

### PR DESCRIPTION
**Pull request by SuryaNJena**
Hello World for Golang and a accompanying README.md file

### CODE REVIEW

**Comment by Hyper-Matrix** [comment]
Great, Do add a description of this PR.

**Comment by SuryaNJena** [comment]
Done (adding a Description to my PR).

**Comment by Hyper-Matrix** [comment]
LGTM...Well done @atulsnjena

**Review by C3Suryansu — APPROVED** [review]
Looks ok.

**Review by rupeshmohanty — COMMENTED** [review]
Looks ok to me!

**Review by trideepb — APPROVED** [review]

**Review by rupeshmohanty — APPROVED** [review]
Works great!

**Pull request merged**
